In [1]:
import numpy as np

In [2]:
### Markov Decision Process for Small Gridworld
# 1) State-space -> self.states
# 2) Action-space -> self.actions
# 3) State transition probabilities -> self.P
# 4) Reward function -> self.rewards

SHAPE = (4,4)
UP, DOWN, LEFT, RIGHT = 0, 1, 2, 3

# Helper function to convert state index from 2d to 1d
def get_state_idx_1d(x,y,shape):
    return x*shape[1]+y

class Gridworld:
    def __init__(self, shape):
        self.shape = shape
        num_states = np.prod(shape)
        num_actions = 4
        self.states = np.arange(num_states)
        self.actions = [UP,DOWN,LEFT,RIGHT]
        self.gamma = 1
        rewards = [-1 for j in range(num_states)]
        rewards[0] = rewards[num_states-1] = 0
        self.rewards = rewards
        
        P = np.zeros((num_states,num_actions,num_states,2)) # for each state-action pair ((x,y), a) => stores P((x',y')) and expected reward
        states = np.arange(num_states).reshape(shape)
        iterator = np.nditer(states, flags=['multi_index'])

        # Probability of next state
        def get_next_state(x,y,a):
            if (x==0 and y==0) or (x==shape[0]-1 and y==shape[1]-1):
                return get_state_idx_1d(x,y,shape)
            nx = x
            ny = y
            if a == UP:
                nx = x-1
            elif a == DOWN:
                nx = x+1
            elif a == LEFT:
                ny = y-1
            else:
                 ny = y+1
            if nx < 0 or nx > shape[0]-1:
                nx = x
            if ny < 0 or ny > shape[1]-1:
                ny = y
            return get_state_idx_1d(nx, ny, shape)

        while not iterator.finished:
            x,y = iterator.multi_index
            cur_state = get_state_idx_1d(x,y,shape)
            for a in {UP,DOWN,LEFT,RIGHT}:
                next_state = get_next_state(x,y,a)
                P[cur_state][a][next_state][0] = 1
                P[cur_state][a][next_state][1] = rewards[cur_state]
            iterator.iternext()

        self.P = P

gridworld = Gridworld(SHAPE)

In [3]:
# Value Iteration Algorithm

def get_value_grid(values):
    n = len(values[0])
    dim = int(n**0.5)
    return np.round(values,2).reshape((dim,dim))

def value_iteration(gridworld, threshold=1e-5):
    states = gridworld.states
    actions = gridworld.actions
    gamma = gridworld.gamma
    n = len(states)
    m = len(actions)

    values = np.random.random((1,n))
    values[0][0] = values[0][n-1] = 0

    iteration_count = 0
    while True:
        delta = 0
        policy = np.zeros((n, m))
        for s in states:
            best_actions = [0]
            max_value = -float('inf')
            for a in actions:
                transition_prob = gridworld.P[s,a,:,0]
                reward_fun = gridworld.P[s,a,:,1]
                action_value = np.multiply(transition_prob,(reward_fun + gamma*values)).sum()
                if action_value > max_value:
                    best_actions = [a]
                    max_value = action_value
            delta = max(delta, abs(max_value-values[0][s]))
            values[0][s] = max_value
            policy[s][best_actions[0]] = 1
        iteration_count += 1
        if delta < threshold:
            break
    
    print("Found optimal policy in {} iterations\n".format(iteration_count))
    print("Optimal policy (action probability distribution):\n{}\n".format(policy))
    print("Optimal state-value function:\n{}\n".format(values))
    print("Optimal state-value function (in grid):\n{}\n".format(get_value_grid(values)))
    return (values,policy)

In [4]:
values, policy = value_iteration(gridworld, threshold=1e-5)

Found optimal policy in 5 iterations

Optimal policy (action probability distribution):
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]

Optimal state-value function:
[[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.]]

Optimal state-value function (in grid):
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

